---
title: "Simulación de procesos estocásticos"
author: "Benjamin Oliva & Omar Alfaro-Rivera"
date: "18/9/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Caminata.R")
```


```{r eruptions, echo=FALSE}
inputPanel(
        
      sliderInput("Time",
                  "Numero de simulaciones:",
                  min = 100,
                  max = 5000,
                  value = 1000),
      
      sliderInput("N",
                  "Numero de caminos:",
                  min = 1,
                  max = 50,
                  value = 25)
)

renderPlot({
    # generate t and N based on input$bins from ui.R
    Soporte <- input$Time
    Moneda <- c(1,-1)
    Caminos <- input$N
    
    # draw the plot with the specified number of t and N
    
    for(i in 1:Caminos){
      TT <- data.matrix(data.frame(Caminata(Moneda, Soporte)[1]))
      #
      G_t <- data.matrix(data.frame(Caminata(Moneda, Soporte)[2]))
      #
      output = plot(TT, G_t, col = "blue", type = "l", ylab = "Ganancias", xlab = "Tiempo", 
                    ylim = c(-150,150), main="Simulacion caminos aleatorios")
      #
      par(new = TRUE)
      #
      i <- i +1}
})
```


```{r tabsets, echo=FALSE}
shinyAppDir(
  system.file("examples/06_tabsets", package = "shiny"),
  options = list(
    width = "100%", height = 550
  )
)
```

